config/routes.rb
require 'devise'
Rails.application.routes.draw do
  
  get 'welcome/index'
  root 'welcome#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :posts
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	
end

app/models/user.rb
require 'devise'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
require 'devise'

class PostsController < ApplicationController

  before_action :authenticate_user!, :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :picture)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sobreˆvoar | Imagens Aéreas</title>
  
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- This site is optimized with the Yoast WordPress SEO plugin v2.0.1 - https://yoast.com/wordpress/plugins/seo/ -->
<title>sobreˆvoar | Imagens Aéreas</title>
<meta name="description" content="Imagens aéreas. Balneario Camboriú."/>
<meta property="og:locale" content="pt_BR" />
<meta property="og:type" content="website" />
<meta property="og:title" content="sobrevoar | Imagens aéreas." />
<meta property="og:description" content="Imagens aéreas. Balneario Camboriú." />
<meta property="og:url" content="http://sobrevoar.me/" />
<meta property="og:site_name" content="sobrevoar | Imagens Aéreas<" />

<!-- / Yoast WordPress SEO plugin. -->

<script type='text/javascript' src='/assets/jquery-1.11.1.js'></script>
<script type='text/javascript' src='/assets/jquery-migrate.min.js'></script>
<script type='text/javascript' src='/assets/jquery-1.10.2.min.js'></script>
<script type='text/javascript' src='/assets/modernizr-2.6.2.min.js'></script>
<script type='text/javascript' src='/assets/bootstrap.min.js'></script>

</head>
<body class="home page page-template-default fade">
<div class="hfeed site">
    <%= yield %>
</div>

</body>

<script type='text/javascript' src='/assets/ie.js'></script>
<script type='text/javascript' src='/assets/analytics.js'></script>
<script type='text/javascript' src='/assets/plugins.js'></script>
<script type='text/javascript' src='/assets/main.js'></script>
</html>

app/views/posts/_form.html.erb
  <%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container-fluid">

	<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div id="content" class="scrollable">
  <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.name %></td>
          <td><%= post.description %></td>
          <td><%= image_tag(post.picture_url, :width => 260) if post.picture.present? %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
	<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
	<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@post.picture_url, :width => 600) if @post.picture.present? %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div id="page" class="hfeed site">
    <header id="masthead" class="site-header" role="banner">
        <nav id="navbar" class="container navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header col-md-3">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand logo" href="http://sobrevoar.me/" rel="home"></a> -->
                <a class="logot" href="http://sobrevoar.me/" rel="home">sobreˆvoar</a>

            </div><!-- /.navbar-header -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="nav-links">
                <div class="collapse navbar-collapse">
                    <ul id="menu-main-navigation" class="nav navbar-nav">
                        <li id="menu-item-70" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-4 current_page_item menu-item-70"><a href="#home">Início</a></li>
                        <li id="menu-item-75" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-75"><a href="#portfolio">Portfolio</a></li>
                        <li id="menu-item-72" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-72"><a href="#historia">Quem somos</a></li><li id="menu-item-71" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-71"><a href="#contato">Contato</a></li>

                    </ul>
                </div>
            </div>
        </nav>

    </header><!-- #masthead -->

    <div id="content" class="site-content" style="margin-top:80px;">

    <div class="parallax">

        <section class="parallax__layer parallax__layer--back">
            <div class="container-fluid slider-height"> 
                <img src="assets/cloud.jpeg" class="hero-img img-responsive">
            </div>
        </section>

        <div class="home-content-block parallax__layer parallax__layer--base">
            <section class="intro-text">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12" id="intro-text">
                            <h3>Imagens aéreas, <br>feitas com pé no chão <br>e paixão por teconologia.</h3>
                        </div>
                    </div>
                </div>
            </section>

            <section class="portfolio-grid text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <a class="col-xs-12 col-sm-6 col-md-4 portfolio-item" href="#tonsai">
                                <div class="color-overlay-placeholder" style="background-image: url('assets/pancakes.jpg');">
                                    <div class="color-overlay" style="background-color: #666666">
                                        <span id="hover-text">Pancake Rocks - Nova Zelândia @ 2014</span>
                                    </div>
                                </div>
                            </a>
                            <a class="col-xs-12 col-sm-6 col-md-4 portfolio-item" href="#tonsai">
                                <div class="color-overlay-placeholder" style="background-image: url('assets/tauranga.jpg');">
                                    <div class="color-overlay" style="background-color: #666666">
                                        <span id="hover-text">Cathedral Cove - Nova Zelândia @ 2014</span>
                                    </div>
                                </div>
                            </a>
                            <a class="col-xs-12 col-sm-6 col-md-4 portfolio-item" href="#tonsai">
                                <div class="color-overlay-placeholder" style="background-image: url('assets/tonsai.png');">
                                    <div class="color-overlay" style="background-color: #666666">
                                        <span id="hover-text">Ilhas aos redores de Tonsai Beach - Thailandia @ 2015</span>
                                    </div>
                                </div>
                            </a>

                            <a class="portfolio-button" href="#portfolio">Mais produções</a>
                        </div>
                    </div>
                </div>
            </section>

            <section class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 text-center" id="grey-box">
                        <div id="grey-box-text" class="col-sm-8 col-sm-offset-2" >
                            <h2>Fotografia e Produções Aéreas</h2>
                            <p>Somos uma empresa especializada em produção de imagens vista por novos ângulos. Os drones vieram para solucionar problemas, trazer novas propostas e fascinantes experiências visuais.</p>
                            <div class="row">
                                <a class="text-center" href="/history">Leia mais</a>
                            </div>
                        </div>

                    </div>
                </div>
            </section>

            <section class="container">
                <div class="col-xs-12" >
                    <div id="home-bottom-image">
                        <div class="col-md-6 text-center" id="vcenter-container">
                            <h2 id="vcenter">Temos muito orgulho de trazer inovação e solução para os mercados de publicidade, engenharia, construção civil, segurança, agronegócio, eventos e tv. 
                            </h2>
                        </div>
                    </div>
                </div>
            </section>

            <footer>
                <div class="container">
                    <div class="row text-center">
                        <h5>sobreˆvoar Photography</h5>
                        <ul class="list-unstyled">
                            <li><a href="tel:11981915980">(11)98191-5980</a></li>
                            <li><a href="tel:4799145170">(47)9914-5170</a></li>
                            <li><a href="mailto:venha@sobrevoar.me">venha@sobrevoar.me</a></li>
                            <li><a href="http://facebook.com/sobre1voar">facebook.com/sobre1voar</a></li>
                        </ul>
                    </div>
                </div>
            </footer>

        </div>
    </div>